#!/usr/bin/env python3
"""Install this toolkit into a Codex project-scoped .codex directory.

The installer does three things:
1. links or copies the toolkit root into `<target> / conch-review-toolkit`
2. generates project-local skill wrappers under `<target> / skills /`
3. renders reviewer specs as Codex subagents under `<target> / agents /`
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
from pathlib import Path


SCRIPT_PATH = Path(__file__).resolve()
REPO_ROOT = SCRIPT_PATH.parent
SKILLS_DIR = REPO_ROOT / "skills"
REVIEWERS_DIR = REPO_ROOT / "reviewers"
DEFAULT_CONCH_CODEX_DIR = Path.home() / "Conch" / ".codex"
TOOLKIT_DIRNAME = REPO_ROOT.name
MANAGED_HEADER = (
    "<!-- Generated by install_codex_toolkit.py. Do not edit by hand. -->"
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Install the current conch-review-toolkit checkout into a Codex "
            "project-scoped .codex directory."
        )
    )
    parser.add_argument(
        "target_codex_dir",
        nargs="?",
        help=(
            "Target Codex directory such as /path/to/Conch/.codex. "
            "Defaults to ~/Conch/.codex when ~/Conch exists."
        ),
    )
    parser.add_argument(
        "--copy-toolkit",
        action="store_true",
        help="Copy the toolkit root into the target instead of symlinking it.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Replace existing generated files or conflicting toolkit installs.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print planned actions without changing the target directory.",
    )
    return parser.parse_args()


def resolve_target_codex_dir(raw_target: str | None) -> Path:
    if raw_target:
        return Path(raw_target).expanduser()
    if DEFAULT_CONCH_CODEX_DIR.parent.exists():
        return DEFAULT_CONCH_CODEX_DIR
    raise SystemExit(
        "No target .codex directory provided and ~/Conch was not found. "
        "Pass an explicit target path, for example: "
        "install_codex_toolkit.py /path/to/Conch/.codex"
    )


def split_frontmatter(text: str) -> tuple[str, str]:
    if not text.startswith("---\n"):
        return "", text
    marker = "\n---\n"
    end = text.find(marker, 4)
    if end == -1:
        return "", text
    frontmatter = text[: end + len(marker)]
    body = text[end + len(marker) :]
    return frontmatter, body


def extract_purpose(markdown: str) -> str:
    match = re.search(
        r"^## Purpose\s+(.*?)(?:\n## |\Z)",
        markdown,
        flags=re.MULTILINE | re.DOTALL,
    )
    if match:
        block = match.group(1).strip()
        paragraph = block.split("\n\n", 1)[0].strip()
        return " ".join(line.strip() for line in paragraph.splitlines())

    paragraphs = [p.strip() for p in markdown.split("\n\n") if p.strip()]
    for paragraph in paragraphs:
        if not paragraph.startswith("#"):
            return " ".join(line.strip() for line in paragraph.splitlines())
    return "Conch reviewer subagent generated from reviewer spec."


def extract_reviewer_names(skill_body: str) -> list[str]:
    names = re.findall(r"reviewers/([a-z0-9-]+)\.md", skill_body)
    seen: dict[str, None] = {}
    for name in names:
        seen.setdefault(name, None)
    return list(seen)


def rewrite_skill_body(skill_body: str, toolkit_root: Path) -> str:
    replacements = {
        "`policies/": f"`{toolkit_root}/policies/",
        "`reviewers/": f"`{toolkit_root}/reviewers/",
        "`scripts/": f"`{toolkit_root}/scripts/",
        "python3 scripts/": f"python3 {toolkit_root}/scripts/",
        "python scripts/": f"python {toolkit_root}/scripts/",
    }
    rewritten = skill_body
    for old, new in replacements.items():
        rewritten = rewritten.replace(old, new)
    return rewritten


def build_skill_wrapper(source_skill: Path, toolkit_root: Path, agents_dir: Path) -> str:
    raw_text = source_skill.read_text(encoding="utf-8")
    frontmatter, body = split_frontmatter(raw_text)
    reviewer_names = extract_reviewer_names(body)
    reviewer_lines = "\n".join(f"- `{name}`" for name in reviewer_names) or "- none"
    rewritten_body = rewrite_skill_body(body.strip(), toolkit_root)

    wrapper_header = f"""{MANAGED_HEADER}

This installed skill wrapper is generated from `{source_skill}`.

Toolkit root for shared assets:
- `{toolkit_root}`

Installed reviewer subagents with matching names:
{reviewer_lines}

Those subagents live under:
- `{agents_dir}`

If a base instruction says to load reviewer specs, prefer the matching installed
Codex subagent when delegation is appropriate. Resolve shared paths under the
toolkit root above.
"""

    parts = [frontmatter.rstrip(), "", wrapper_header.strip(), "", rewritten_body]
    return "\n".join(part for part in parts if part) + "\n"


def build_agent_toml(reviewer_path: Path, toolkit_root: Path) -> str:
    reviewer_name = reviewer_path.stem
    reviewer_spec = reviewer_path.read_text(encoding="utf-8").strip()
    description = extract_purpose(reviewer_spec)
    developer_instructions = (
        f"You are `{reviewer_name}`, a project-local Codex subagent installed "
        f"from the Conch Review Toolkit.\n\n"
        "Stay within the reviewer boundary defined below. Treat the reviewer "
        "spec as authoritative.\n"
        f"When the spec references `<toolkit_root>`, use `{toolkit_root}`.\n"
        "Prefer read-only analysis unless the parent agent explicitly asks for "
        "edits.\n"
        "Cite concrete evidence with file paths and line numbers where "
        "possible.\n"
        "If runtime execution is needed but unavailable, say so clearly instead "
        "of guessing.\n\n"
        "Reviewer spec:\n\n"
        f"{reviewer_spec.replace('<toolkit_root>', str(toolkit_root))}\n"
    )

    return "\n".join(
        [
            f'name = {json.dumps(reviewer_name)}',
            f"description = {json.dumps(description)}",
            'model = "gpt-5.4"',
            'model_reasoning_effort = "high"',
            'sandbox_mode = "read-only"',
            f"developer_instructions = {json.dumps(developer_instructions)}",
            "",
        ]
    )


def remove_path(path: Path, *, dry_run: bool) -> None:
    if dry_run:
        return
    if path.is_symlink() or path.is_file():
        path.unlink()
    elif path.is_dir():
        shutil.rmtree(path)


def ensure_directory(path: Path, *, dry_run: bool) -> None:
    if dry_run:
        return
    path.mkdir(parents=True, exist_ok=True)


def write_text(path: Path, text: str, *, dry_run: bool) -> None:
    if dry_run:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def install_toolkit_root(
    target_codex_dir: Path,
    *,
    copy_toolkit: bool,
    force: bool,
    dry_run: bool,
) -> Path:
    installed_root = target_codex_dir / TOOLKIT_DIRNAME

    if installed_root.exists() or installed_root.is_symlink():
        current_target = None
        if installed_root.is_symlink():
            current_target = installed_root.resolve(strict=False)
        if current_target == REPO_ROOT.resolve():
            return installed_root
        if not force:
            raise SystemExit(
                f"{installed_root} already exists. Re-run with --force to replace it."
            )
        remove_path(installed_root, dry_run=dry_run)

    if dry_run:
        return installed_root

    if copy_toolkit:
        shutil.copytree(REPO_ROOT, installed_root, symlinks=True, dirs_exist_ok=False)
    else:
        installed_root.symlink_to(REPO_ROOT, target_is_directory=True)
    return installed_root


def install_skill_wrappers(
    target_codex_dir: Path,
    toolkit_root: Path,
    *,
    force: bool,
    dry_run: bool,
) -> list[Path]:
    skills_target = target_codex_dir / "skills"
    agents_dir = target_codex_dir / "agents"
    ensure_directory(skills_target, dry_run=dry_run)
    installed: list[Path] = []

    for source_skill in sorted(SKILLS_DIR.glob("*/SKILL.md")):
        skill_name = source_skill.parent.name
        wrapper_dir = skills_target / skill_name
        wrapper_path = wrapper_dir / "SKILL.md"

        if wrapper_dir.exists() and not wrapper_dir.is_dir():
            if not force:
                raise SystemExit(
                    f"{wrapper_dir} exists and is not a directory. Use --force to replace it."
                )
            remove_path(wrapper_dir, dry_run=dry_run)

        ensure_directory(wrapper_dir, dry_run=dry_run)
        if wrapper_path.exists() and not force:
            existing = wrapper_path.read_text(encoding="utf-8")
            if MANAGED_HEADER not in existing:
                raise SystemExit(
                    f"{wrapper_path} already exists and is not managed by this installer. "
                    "Use --force to replace it."
                )

        wrapper_text = build_skill_wrapper(source_skill, toolkit_root, agents_dir)
        write_text(wrapper_path, wrapper_text, dry_run=dry_run)
        installed.append(wrapper_path)

    return installed


def install_agents(
    target_codex_dir: Path,
    toolkit_root: Path,
    *,
    force: bool,
    dry_run: bool,
) -> list[Path]:
    agents_target = target_codex_dir / "agents"
    ensure_directory(agents_target, dry_run=dry_run)
    installed: list[Path] = []

    for reviewer_path in sorted(REVIEWERS_DIR.glob("*.md")):
        if reviewer_path.name == "README.md":
            continue
        agent_path = agents_target / f"{reviewer_path.stem}.toml"
        if agent_path.exists() and not force:
            existing = agent_path.read_text(encoding="utf-8")
            if "Conch Review Toolkit" not in existing:
                raise SystemExit(
                    f"{agent_path} already exists and is not managed by this installer. "
                    "Use --force to replace it."
                )

        agent_toml = build_agent_toml(reviewer_path, toolkit_root)
        write_text(agent_path, agent_toml, dry_run=dry_run)
        installed.append(agent_path)

    return installed


def main() -> int:
    args = parse_args()
    target_codex_dir = resolve_target_codex_dir(args.target_codex_dir)

    if target_codex_dir.name != ".codex":
        print(
            f"warning: target path does not end with '.codex': {target_codex_dir}",
            file=sys.stderr,
        )

    ensure_directory(target_codex_dir, dry_run=args.dry_run)
    toolkit_root = install_toolkit_root(
        target_codex_dir,
        copy_toolkit=args.copy_toolkit,
        force=args.force,
        dry_run=args.dry_run,
    )
    installed_skills = install_skill_wrappers(
        target_codex_dir,
        toolkit_root,
        force=args.force,
        dry_run=args.dry_run,
    )
    installed_agents = install_agents(
        target_codex_dir,
        toolkit_root,
        force=args.force,
        dry_run=args.dry_run,
    )

    action = "Would install" if args.dry_run else "Installed"
    print(f"{action} toolkit root: {toolkit_root}")
    print(f"{action.lower()} {len(installed_skills)} skill wrapper(s):")
    for path in installed_skills:
        print(f"  - {path}")
    print(f"{action.lower()} {len(installed_agents)} subagent(s):")
    for path in installed_agents:
        print(f"  - {path}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
